name = "secure-audit-frontend"
compatibility_date = "2024-01-01"

[env.production]
name = "secure-audit-frontend"
compatibility_date = "2024-01-01"

[env.production.vars]
VITE_API_URL = "https://secure-audit-backend.onrender.com/api" 